/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppStatsRouteImport } from './routes/_authenticated/app.stats'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppQuizRouteImport } from './routes/_authenticated/app.quiz'
import { Route as AuthenticatedAppPodcastRouteImport } from './routes/_authenticated/app.podcast'
import { Route as AuthenticatedAppPlanRouteImport } from './routes/_authenticated/app.plan'
import { Route as AuthenticatedAppNotesRouteImport } from './routes/_authenticated/app.notes'
import { Route as AuthenticatedAppMindmapRouteImport } from './routes/_authenticated/app.mindmap'
import { Route as AuthenticatedAppGossipRouteImport } from './routes/_authenticated/app.gossip'
import { Route as AuthenticatedAppFlashcardsRouteImport } from './routes/_authenticated/app.flashcards'
import { Route as AuthenticatedAppEssayRouteImport } from './routes/_authenticated/app.essay'
import { Route as AuthenticatedAppCommunityRouteImport } from './routes/_authenticated/app.community'
import { Route as AuthenticatedAppChatRouteImport } from './routes/_authenticated/app.chat'
import { Route as AuthenticatedAppBrainrotRouteImport } from './routes/_authenticated/app.brainrot'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppStatsRoute = AuthenticatedAppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppQuizRoute = AuthenticatedAppQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPodcastRoute = AuthenticatedAppPodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPlanRoute = AuthenticatedAppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNotesRoute = AuthenticatedAppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMindmapRoute = AuthenticatedAppMindmapRouteImport.update({
  id: '/mindmap',
  path: '/mindmap',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppGossipRoute = AuthenticatedAppGossipRouteImport.update({
  id: '/gossip',
  path: '/gossip',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFlashcardsRoute =
  AuthenticatedAppFlashcardsRouteImport.update({
    id: '/flashcards',
    path: '/flashcards',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEssayRoute = AuthenticatedAppEssayRouteImport.update({
  id: '/essay',
  path: '/essay',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCommunityRoute =
  AuthenticatedAppCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChatRoute = AuthenticatedAppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBrainrotRoute =
  AuthenticatedAppBrainrotRouteImport.update({
    id: '/brainrot',
    path: '/brainrot',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/brainrot': typeof AuthenticatedAppBrainrotRoute
  '/app/chat': typeof AuthenticatedAppChatRoute
  '/app/community': typeof AuthenticatedAppCommunityRoute
  '/app/essay': typeof AuthenticatedAppEssayRoute
  '/app/flashcards': typeof AuthenticatedAppFlashcardsRoute
  '/app/gossip': typeof AuthenticatedAppGossipRoute
  '/app/mindmap': typeof AuthenticatedAppMindmapRoute
  '/app/notes': typeof AuthenticatedAppNotesRoute
  '/app/plan': typeof AuthenticatedAppPlanRoute
  '/app/podcast': typeof AuthenticatedAppPodcastRoute
  '/app/quiz': typeof AuthenticatedAppQuizRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/stats': typeof AuthenticatedAppStatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/brainrot': typeof AuthenticatedAppBrainrotRoute
  '/app/chat': typeof AuthenticatedAppChatRoute
  '/app/community': typeof AuthenticatedAppCommunityRoute
  '/app/essay': typeof AuthenticatedAppEssayRoute
  '/app/flashcards': typeof AuthenticatedAppFlashcardsRoute
  '/app/gossip': typeof AuthenticatedAppGossipRoute
  '/app/mindmap': typeof AuthenticatedAppMindmapRoute
  '/app/notes': typeof AuthenticatedAppNotesRoute
  '/app/plan': typeof AuthenticatedAppPlanRoute
  '/app/podcast': typeof AuthenticatedAppPodcastRoute
  '/app/quiz': typeof AuthenticatedAppQuizRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/stats': typeof AuthenticatedAppStatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/brainrot': typeof AuthenticatedAppBrainrotRoute
  '/_authenticated/app/chat': typeof AuthenticatedAppChatRoute
  '/_authenticated/app/community': typeof AuthenticatedAppCommunityRoute
  '/_authenticated/app/essay': typeof AuthenticatedAppEssayRoute
  '/_authenticated/app/flashcards': typeof AuthenticatedAppFlashcardsRoute
  '/_authenticated/app/gossip': typeof AuthenticatedAppGossipRoute
  '/_authenticated/app/mindmap': typeof AuthenticatedAppMindmapRoute
  '/_authenticated/app/notes': typeof AuthenticatedAppNotesRoute
  '/_authenticated/app/plan': typeof AuthenticatedAppPlanRoute
  '/_authenticated/app/podcast': typeof AuthenticatedAppPodcastRoute
  '/_authenticated/app/quiz': typeof AuthenticatedAppQuizRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/stats': typeof AuthenticatedAppStatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/app'
    | '/app/brainrot'
    | '/app/chat'
    | '/app/community'
    | '/app/essay'
    | '/app/flashcards'
    | '/app/gossip'
    | '/app/mindmap'
    | '/app/notes'
    | '/app/plan'
    | '/app/podcast'
    | '/app/quiz'
    | '/app/settings'
    | '/app/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/app'
    | '/app/brainrot'
    | '/app/chat'
    | '/app/community'
    | '/app/essay'
    | '/app/flashcards'
    | '/app/gossip'
    | '/app/mindmap'
    | '/app/notes'
    | '/app/plan'
    | '/app/podcast'
    | '/app/quiz'
    | '/app/settings'
    | '/app/stats'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/app/brainrot'
    | '/_authenticated/app/chat'
    | '/_authenticated/app/community'
    | '/_authenticated/app/essay'
    | '/_authenticated/app/flashcards'
    | '/_authenticated/app/gossip'
    | '/_authenticated/app/mindmap'
    | '/_authenticated/app/notes'
    | '/_authenticated/app/plan'
    | '/_authenticated/app/podcast'
    | '/_authenticated/app/quiz'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/stats': {
      id: '/_authenticated/app/stats'
      path: '/stats'
      fullPath: '/app/stats'
      preLoaderRoute: typeof AuthenticatedAppStatsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/quiz': {
      id: '/_authenticated/app/quiz'
      path: '/quiz'
      fullPath: '/app/quiz'
      preLoaderRoute: typeof AuthenticatedAppQuizRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/podcast': {
      id: '/_authenticated/app/podcast'
      path: '/podcast'
      fullPath: '/app/podcast'
      preLoaderRoute: typeof AuthenticatedAppPodcastRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/plan': {
      id: '/_authenticated/app/plan'
      path: '/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AuthenticatedAppPlanRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notes': {
      id: '/_authenticated/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AuthenticatedAppNotesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/mindmap': {
      id: '/_authenticated/app/mindmap'
      path: '/mindmap'
      fullPath: '/app/mindmap'
      preLoaderRoute: typeof AuthenticatedAppMindmapRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/gossip': {
      id: '/_authenticated/app/gossip'
      path: '/gossip'
      fullPath: '/app/gossip'
      preLoaderRoute: typeof AuthenticatedAppGossipRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/flashcards': {
      id: '/_authenticated/app/flashcards'
      path: '/flashcards'
      fullPath: '/app/flashcards'
      preLoaderRoute: typeof AuthenticatedAppFlashcardsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/essay': {
      id: '/_authenticated/app/essay'
      path: '/essay'
      fullPath: '/app/essay'
      preLoaderRoute: typeof AuthenticatedAppEssayRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/community': {
      id: '/_authenticated/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AuthenticatedAppCommunityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat': {
      id: '/_authenticated/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AuthenticatedAppChatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/brainrot': {
      id: '/_authenticated/app/brainrot'
      path: '/brainrot'
      fullPath: '/app/brainrot'
      preLoaderRoute: typeof AuthenticatedAppBrainrotRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppBrainrotRoute: typeof AuthenticatedAppBrainrotRoute
  AuthenticatedAppChatRoute: typeof AuthenticatedAppChatRoute
  AuthenticatedAppCommunityRoute: typeof AuthenticatedAppCommunityRoute
  AuthenticatedAppEssayRoute: typeof AuthenticatedAppEssayRoute
  AuthenticatedAppFlashcardsRoute: typeof AuthenticatedAppFlashcardsRoute
  AuthenticatedAppGossipRoute: typeof AuthenticatedAppGossipRoute
  AuthenticatedAppMindmapRoute: typeof AuthenticatedAppMindmapRoute
  AuthenticatedAppNotesRoute: typeof AuthenticatedAppNotesRoute
  AuthenticatedAppPlanRoute: typeof AuthenticatedAppPlanRoute
  AuthenticatedAppPodcastRoute: typeof AuthenticatedAppPodcastRoute
  AuthenticatedAppQuizRoute: typeof AuthenticatedAppQuizRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppStatsRoute: typeof AuthenticatedAppStatsRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppBrainrotRoute: AuthenticatedAppBrainrotRoute,
  AuthenticatedAppChatRoute: AuthenticatedAppChatRoute,
  AuthenticatedAppCommunityRoute: AuthenticatedAppCommunityRoute,
  AuthenticatedAppEssayRoute: AuthenticatedAppEssayRoute,
  AuthenticatedAppFlashcardsRoute: AuthenticatedAppFlashcardsRoute,
  AuthenticatedAppGossipRoute: AuthenticatedAppGossipRoute,
  AuthenticatedAppMindmapRoute: AuthenticatedAppMindmapRoute,
  AuthenticatedAppNotesRoute: AuthenticatedAppNotesRoute,
  AuthenticatedAppPlanRoute: AuthenticatedAppPlanRoute,
  AuthenticatedAppPodcastRoute: AuthenticatedAppPodcastRoute,
  AuthenticatedAppQuizRoute: AuthenticatedAppQuizRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppStatsRoute: AuthenticatedAppStatsRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
